name: Demo Workflow

on:
  push:
    branches:
      - 'main'
      - 'feature/**'
jobs:
  demo-job:
    name: Demo Job
    runs-on: ubuntu-latest
    steps:
      - name: Message 1
        run: echo "This is Message 1"
      - name: Message 2
        run: echo "Thois is Message 2"
